version: "3.9"

services:

  traefik:
    image: traefik:v3.0

    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=dimazum@mail.ru"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"

      - "--api.dashboard=true"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt

    restart: unless-stopped

    networks:
      - traefik_proxy

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.stut.mooo.com`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=le"

      - "traefik.http.routers.traefik-dashboard.service=api@internal"

      - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$apr1$$j801xo4j$$psVjjf0i/.qYlEJKtH/yN/"
      - "traefik.http.routers.traefik-dashboard.middlewares=dashboard-auth"

networks:
  traefik_proxy:
    external: true