version: "3.9"
services:
  backend:
    build: backend
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - 5000:80
  client:
    image: angular-client
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - 5001:4200
    
  proxy:
    image: nginx:1.21-alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/www:/var/www/certbot
      - ./proxy/ssl:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    command: ["nginx", "-g", "daemon off;"]

  certbot:
    image: certbot/certbot
    volumes:
      - ./proxy/www:/var/www/certbot
      - ./proxy/ssl:/etc/letsencrypt
    entrypoint: /bin/sh
    command: -c "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /var/www/certbot; done"


  stut.database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: stut.database
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - ./data:/var/opt/mssql/data
