version: "3.9"

services:
  traefik:
    image: traefik:v3.6.2
    container_name: traefik

    command:
      # Docker provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # HTTP → HTTPS redirect
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      # API + dashboard
      - "--api=true"
      - "--api.dashboard=true"

      # ACME (DuckDNS DNS challenge)
      - "--certificatesresolvers.le.acme.email=dimazum@mail.ru"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=duckdns"

      # logs (чтобы видеть что происходит)
      - "--log.level=INFO"

    environment:
      - DUCKDNS_TOKEN=94c2bbb8-cccb-4b3a-ac1d-c6075c9a91a6
      - DUCKDNS_DOMAINS=stut

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt

    networks:
      - traefik_proxy

    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"

      # ---------------------------
      # Dashboard (traefik subdomain)
      # ---------------------------
      - "traefik.http.routers.traefik.rule=Host(`traefik.stut.duckdns.org`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.service=api@internal"

      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$j801xo4j$$psVjjf0i/.qYlEJKtH/yN/"
      - "traefik.http.routers.traefik.middlewares=auth"

      # ---------------------------
      # Root domain (stut.duckdns.org)
      # просто тестовый сервис (чтобы был HTTPS)
      # ---------------------------
      - "traefik.http.routers.root.rule=Host(`stut.duckdns.org`)"
      - "traefik.http.routers.root.entrypoints=websecure"
      - "traefik.http.routers.root.tls=true"
      - "traefik.http.routers.root.tls.certresolver=le"
      - "traefik.http.routers.root.service=api@internal"

networks:
  traefik_proxy:
    external: true