version: "3.9"

services:
  # ========================
  # Traefik
  # ========================
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=dimazum@mail.ru"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    restart: unless-stopped

  # ========================
  # Backend (.NET 10)
  # ========================
  backend:
    build: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - COMMIT_HASH=${COMMIT_HASH}
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - audio_data:/app/Uploads
    depends_on:
      - rabbitmq
    ports:
      - "5000:80"  # для дебага
    labels:
      - "traefik.enable=true"

      # API
      - "traefik.http.routers.backend-api.rule=Host(`stut.mooo.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend-api.entrypoints=websecure"
      - "traefik.http.routers.backend-api.tls.certresolver=le"

      # voice-analysis
      - "traefik.http.routers.backend-voice.rule=Host(`stut.mooo.com`) && PathPrefix(`/voice-analysis`)"
      - "traefik.http.routers.backend-voice.entrypoints=websecure"
      - "traefik.http.routers.backend-voice.tls.certresolver=le"

      # FRONTEND
      - "traefik.http.routers.backend-frontend.rule=Host(`stut.mooo.com`)"
      - "traefik.http.routers.backend-frontend.entrypoints=websecure"
      - "traefik.http.routers.backend-frontend.tls.certresolver=le"

      - "traefik.http.services.backend.loadbalancer.server.port=80"

  # ========================
  # Voice Analyzer
  # ========================
  voice-analyzer:
    build: ./voice-analyzer
    container_name: voice.analyzer
    environment:
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - audio_data:/audio
    ports:
      - "8001:8000"  # для дебага
    depends_on:
      - rabbitmq
    restart: unless-stopped

  # ========================
  # RabbitMQ
  # ========================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  # ========================
  # Frontend Builder (Angular)
  # ========================
  frontend-builder:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-builder
    volumes:
      - ./backend/stutvds/wwwroot:/app/wwwroot
    command: >
      sh -c "cp -r /app/dist/angular1/browser/* /app/wwwroot/"
    restart: "no"


volumes:
  audio_data:
  rabbitmq_data:
