services:

  backend:
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.backend-preprod.rule=Host(`dev.stut.mooo.com`)"
      - "traefik.http.routers.backend-preprod.entrypoints=websecure"
      - "traefik.http.routers.backend-preprod.tls.certresolver=le"

      - "traefik.http.services.backend-preprod.loadbalancer.server.port=80"

      - "traefik.docker.network=traefik_proxy"

    networks:
      - default
      - traefik_proxy

  stut.database:
    volumes:
      - sql_preprod_data:/var/opt/mssql

volumes:
  sql_preprod_data:

networks:
  traefik_proxy:
    external: true