version: "3.9"

services:

  backend:
    build: backend

    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENV}
      - COMMIT_HASH=${COMMIT_HASH}
      - RABBITMQ_HOST=rabbitmq
      - Mailgun__ApiKey=${Mailgun__ApiKey}
      - ConnectionStrings__Database=${ConnectionStrings__Database}
      - DOCKER_API_VERSION=${DOCKER_API_VERSION}
      - TRAEFIK_PROVIDERS_DOCKER_VERSION=${TRAEFIK_PROVIDERS_DOCKER_VERSION}

    volumes:
      - audio_data:/app/Uploads

    depends_on:
      - rabbitmq
      - stut.database

    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management

    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    restart: unless-stopped

  stut.database:
    image: mcr.microsoft.com/mssql/server:2017-latest

    environment:
      - SA_PASSWORD=${DB_PASSWORD}
      - ACCEPT_EULA=Y

    volumes:
      - sql_data:/var/opt/mssql

    restart: unless-stopped

  frontend-builder:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    volumes:
      - ./backend/stutvds/wwwroot/angular:/app/wwwroot/angular

    command: >
      sh -c "
      rm -rf /app/wwwroot/angular/* &&
      npm ci &&
      npm run build:prod &&
      cp -r /app/dist/angular1/browser/* /app/wwwroot/angular/
      "

    restart: "no"

volumes:
  audio_data:
  rabbitmq_data:
  sql_data: