version: "3.9"

services:

  # ========================
  # Traefik (один на сервер)
  # ========================
  traefik:
    image: traefik:v3.0
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=dimazum@mail.ru"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--api.dashboard=true"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt

    restart: unless-stopped

  # ========================
  # Backend (.NET)
  # ========================
  backend:
    build: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENV}
      - COMMIT_HASH=${COMMIT_HASH}
      - RABBITMQ_HOST=rabbitmq
      - ConnectionStrings__Database=Server=stut.database;Database=stut;User Id=sa;Password=Pass@word;

    volumes:
      - audio_data:/app/Uploads

    depends_on:
      - rabbitmq
      - stut.database

    restart: unless-stopped

  # ========================
  # Voice Analyzer
  # ========================
  voice-analyzer:
    build: ./voice-analyzer
    environment:
      - RABBITMQ_HOST=rabbitmq

    volumes:
      - audio_data:/audio

    depends_on:
      - rabbitmq

    restart: unless-stopped

  # ========================
  # RabbitMQ
  # ========================
  rabbitmq:
    image: rabbitmq:3-management

    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    restart: unless-stopped

  # ========================
  # SQL Server
  # ========================
  stut.database:
    image: mcr.microsoft.com/mssql/server:2017-latest

    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y

    volumes:
      - sql_data:/var/opt/mssql

    restart: unless-stopped

  frontend-builder:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./backend/stutvds/wwwroot/angular:/app/wwwroot/angular
    command:
      sh -c "rm -rf /app/wwwroot/angular/* &&
             npm ci &&
             npm run build:prod &&
             cp -r /app/dist/angular1/browser/* /app/wwwroot/angular/"
    restart: "no"


volumes:
  audio_data:
  rabbitmq_data:
  sql_data: