version: "3.9"
services:
  backend:
    build: backend
  proxy:
    image: nginx:1.21-alpine
    volumes:
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 8080:80
    - 443:443
    command: ["nginx", "-g", "daemon off;"]
