version: "3.9"
services:
  backend:
    build: backend
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - 5000:80
  client:
    image: angular-client
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - 5001:4200
    
  proxy:
    image: nginx:1.21-alpine
    volumes:
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 8080:80
    - 443:443
    - 1433:1433
    command: ["nginx", "-g", "daemon off;"]

  stut.database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: stut.database
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    expose:
      - "5434"
      - "1433"
    volumes:
      - ./data:/var/opt/mssql/data
