services:

  backend:
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.backend-prod.rule=Host(`stut.mooo.com`)"
      - "traefik.http.routers.backend-prod.entrypoints=websecure"
      - "traefik.http.routers.backend-prod.tls.certresolver=le"

      - "traefik.http.services.backend-prod.loadbalancer.server.port=80"

      - "traefik.docker.network=traefik_proxy"

    networks:
      - default
      - traefik_proxy

  stut.database:
    volumes:
      - sql_prod_data:/var/opt/mssql
    ports:
      - "5434:1433"

volumes:
  sql_prod_data:

networks:
  traefik_proxy:
    external: true