# renew_before_expiry = 30 days
version = 2.11.0
archive_dir = /etc/letsencrypt/archive/stut.mooo.com
cert = /etc/letsencrypt/live/stut.mooo.com/cert.pem
privkey = /etc/letsencrypt/live/stut.mooo.com/privkey.pem
chain = /etc/letsencrypt/live/stut.mooo.com/chain.pem
fullchain = /etc/letsencrypt/live/stut.mooo.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = c2c9945f4163597bd6d8732f37590e72
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
stut.mooo.com = /var/www/certbot
